name: ReleaseBuildPopinSeller

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set Secret Properties
      env:
        LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES_PRODUCTION }}
      run: echo "$LOCAL_PROPERTIES" > ./local.properties
    - name: Decode Keystore
      env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/popin.jks
    - name: Running linter
      run: ./gradlew lint
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: build prod
      run: ./gradlew app:bundleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    - name: Upload
      uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: Build Artifacts
        path: app/build/outputs/
    - name: Building debug
      run: ./gradlew app:assembleDebug
    - uses: MeilCli/slack-upload-file@v3
      with:
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: C04M527K2FQ
          file_path: app/build/outputs/apk/debug/app-debug.apk
          initial_comment: Production debug build for Popin-Seller-Android
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

